// tempates/vue/src/lib/BasicLayout/index.vue
<template>
  <div :class="$style.BasicLayout">
    <div :class="menuClassName">
      <a-menu
        :class="$style.Menu"
        :selected-keys="defaultSelectedKeys.map((t) => t.path)"
        :open-keys="defaultOpenKeys.map((t) => t.path)"
        mode="inline"
        theme="dark"
        @openChange="openChange"
        @select="onSelect"
      >
        <template v-for="r in routes">
          <sub-menu v-if="isSubMenu(r)" :key="r.path" :router="r" :$style="$style" />

          <a-menu-item v-else :key="r.path">
            <router-link :to="r.path">
              <a-tooltip :title="r.name" placement="right">
                <img v-if="!!r.icon" alt="" :class="$style.MenuIcon" :src="r.icon" />
                <span :class="$style.MenuIconText">{{ r.name }}</span>
              </a-tooltip>
            </router-link>
          </a-menu-item>
        </template>
      </a-menu>
    </div>

    <div :class="$style.Auto">
      <div :class="$style.BreadcrumbWrap">
        <a-breadcrumb separator="/">
          <a-breadcrumb-item>{{ name }}</a-breadcrumb-item>
          <a-breadcrumb-item v-for="t in breadcrumbPaths()" :key="t.path">
            <router-link :key="t.path" :to="t.path">{{ t.name }}</router-link>
          </a-breadcrumb-item>
        </a-breadcrumb>
      </div>

      <div>
        <keep-alive>
          <router-view></router-view>
        </keep-alive>
      </div>

      <div :class="$style.FooterWrap">
        <Footer />
      </div>
    </div>
  </div>
</template>

<script>
import classNames from 'classnames';
import SubMenu from './SubMenu';
import Footer from '@/lib/Footer';
import Util from './Util';

export default {
  components: {
    'sub-menu': SubMenu,
    Footer,
  },
  props: {
    routes: {
      type: Array,
      default: () => [],
    },
    name: {
      type: String,
      default: '',
    },
  },
  data() {
    return {
      authorized: [],
      isMenuCollapse: false,

      selectedKeys: [],
      openKeys: [],
    };
  },
  computed: {
    defaultSelectedKeys() {
      return this.getDefault().defaultSelectedKeys;
    },
    defaultOpenKeys() {
      return this.getDefault().defaultOpenKeys;
    },
    menuClassName() {
      const { isMenuCollapse, $style } = this;
      return classNames($style.Fixed, $style.Sider, isMenuCollapse ? $style.Collapse : '');
    },
  },
  methods: {
    /**
     * getDefault
     * @return {{defaultOpenKeys: Array, defaultSelectedKeys: Array}}
     */
    getDefault() {
      const { routes = [], openKeys, selectedKeys } = this;
      const defaultSelectedKeys = [];
      const defaultOpenKeys = [];

      Util.loopRoutes({
        defaultOpenKeys,
        defaultSelectedKeys,
        routes: routes.filter((t) => !t.redirect),
      });

      return {
        defaultSelectedKeys: selectedKeys.length ? selectedKeys : defaultSelectedKeys,
        defaultOpenKeys: openKeys.length ? openKeys : defaultOpenKeys,
      };
    },
    /**
     * openChange
     * @param openKeys
     */
    openChange(openKeys) {
      const { routes = [] } = this;
      this.openKeys = openKeys.map((key) => Util.fillKey(key, routes));
    },
    /**
     * onSelect
     * @param selectedKeys
     */
    onSelect({ selectedKeys }) {
      const { routes = [] } = this;
      this.selectedKeys = selectedKeys.map((key) => Util.fillKey(key, routes));
    },
    /**
     * isSubMenu
     * @param r
     * @return {boolean}
     */
    isSubMenu(r) {
      return Util.isSubMenu(r);
    },
    breadcrumbPaths() {
      const { routes } = this;

      const selectKey = window.location.pathname;

      const path = [];
      Util.getPathBySelectKey({
        path,
        routes,
        selectKey,
      });

      return path.filter((t) => !t.redirect);
    },
  },
};
</script>

<style lang="less" module>
.BasicLayout {
  display: flex;
  width: 100%;
  height: 100%;

  > .Auto {
    flex-direction: column;

    > .Fixed {
      padding: 20px;
    }

    //> .Auto {
    //  //min-height: 0;
    //  overflow-y: auto;
    //  background: @common-block-background-color;
    //}
  }

  .Fixed {
    flex-shrink: 0;
    width: 300px;
    .Menu {
      width: 100%;
      height: 100%;
      overflow-y: auto;
    }
  }

  .Auto {
    position: relative;
    display: flex;
    flex-grow: 1;
    min-width: 0;
    overflow-y: auto;
  }
}

.MenuIcon {
  margin-right: 15px;
}

.MenuIconText {
  vertical-align: middle;
}

.Sider {
  transition: all 0.2s;
}

.Collapse {
  width: 51px;
  overflow-x: hidden;
}

.BreadcrumbWrap {
  width: 100%;
  padding: 10px 20px;
}
</style>

// tempates/react/src/lib/BasicLayout/index.jsx
import { Decorators, Dict } from '@baifendian/adhere';
import { Link } from '@ctsj/router';
import { Breadcrumb, Menu, Tooltip } from 'antd';
import classNames from 'classnames';
import pathToRegexp from 'path-to-regexp';
import PropTypes from 'prop-types';
import React from 'react';
import Footer from '@/lib/Footer';

import styles from './index.less';

const { SubMenu } = Menu;

function isAuthority(authoritys = [], allAuthority = []) {
  return authoritys.some((authority) => allAuthority.includes(authority));
}

/**
 * BasicLayout
 * @class BasicLayout
 * @classdesc BasicLayout
 */
@Decorators.ReactErrorBoundaries
class BasicLayout extends React.Component {
  state = {
    authorized: [],
    isMenuCollapse: false,

    selectedKeys: [],
    openKeys: [],
  };

  /**
   * fillKey
   * @param key
   * @param routes
   * @return {{path: *, name: *}}
   */
  static fillKey(key, routes) {
    let entry;
    for (let i = 0; i < routes.length; i++) {
      const item = routes[i];
      if (item.path === key) {
        entry = {
          name: item.name,
          path: item.path,
        };
        break;
      }

      if (item.routes) {
        entry = BasicLayout.fillKey(key, item.routes);
        if (entry) break;
      }
    }

    return entry;
  }

  /**
   * renderTitle
   * @param name
   * @param icon
   * @return {*}
   */
  static renderTitle({ name, icon }) {
    return (
      <Tooltip title={name} placement="right">
        {icon ? <img src={icon} className={styles.MenuIcon} alt="" /> : null}
        <span className={styles.MenuIconText}>{name}</span>
      </Tooltip>
    );
  }

  /**
   * getPathBySelectKey
   * @param path
   * @param routes
   * @param selectKey
   */
  static getPathBySelectKey({ path, routes, selectKey }) {
    for (let i = 0; i < routes.length; i++) {
      const item = routes[i];

      if ('redirect' in item) continue;

      const keys = [];

      // 通过路由中定义的path生成正则表达式
      const reg = pathToRegexp(item.path, keys, {
        sensitive: false, // When true the route will be case sensitive. (default: false)
        strict: false, // When false the trailing slash is optional. (default: false)
        end: false, // When false the path will match at the beginning. (default: true)
        delimiter: '/', // Set the default delimiter for repeat parameters. (default: '/')
      });

      if (reg.test(selectKey)) {
        path.push(item);
      }

      if (item.routes) {
        BasicLayout.getPathBySelectKey({ path, routes: item.routes, selectKey });
      }
    }
  }

  /**
   * loopRoutes
   * @param defaultOpenKeys
   * @param defaultSelectedKeys
   * @param routes
   */
  static loopRoutes({ defaultOpenKeys, defaultSelectedKeys, routes }) {
    const { pathname } = window.location;
    for (let i = 0; i < routes.length; i++) {
      const route = routes[i];
      if (pathname.indexOf(route.path) !== -1) {
        if (
          route.routes &&
          route.routes.length &&
          route.routes.filter((t) => t.hide).length !== route.routes.length
        ) {
          defaultOpenKeys.push({
            path: route.path,
            name: route.name,
          });
          BasicLayout.loopRoutes({ defaultOpenKeys, defaultSelectedKeys, routes: route.routes });
        } else {
          if (pathname === route.path) {
            // 如果是hide，找到第一个不是hide的route
            if ('hide' in route && route.hide) {
              const firstIncludeRoute = routes
                .filter((t) => !('redirect' in t))
                .find((r) => (!('hide' in r) || !r.hide) && pathname.indexOf(r.path) !== -1);

              if (firstIncludeRoute) {
                defaultSelectedKeys.push({
                  path: firstIncludeRoute.path,
                  name: firstIncludeRoute.name,
                });
              }
            } else {
              defaultSelectedKeys.push({
                path: route.path,
                name: route.name,
              });
            }
          }
        }
      }
    }
  }

  async componentDidMount() {
    this.setState({
      authorized: await Dict.value.SystemAuthorized.value,
    });
  }

  /**
   * renderMenuItem
   * @param routes
   * @return {any[]}
   */
  renderMenuItem(routes = []) {
    return routes
      .filter((r) => {
        if ('hide' in r && r.hide) return false;

        if (!r.redirect) {
          if (r.authority && r.authority.length) {
            return isAuthority(r.authority, this.state.authorized);
          }
          return true;
        }
        return false;
      })
      .map((r) => {
        if (
          r.routes &&
          r.routes.length &&
          r.routes.filter((t) => t.hide).length !== r.routes.length
        ) {
          return (
            <SubMenu title={BasicLayout.renderTitle(r)} key={r.path}>
              {this.renderMenuItem(r.routes)}
            </SubMenu>
          );
        }
        return (
          <Menu.Item key={r.path}>
            <Link to={r.path}>{BasicLayout.renderTitle(r)}</Link>
          </Menu.Item>
        );
      });
  }

  renderMenuBar() {
    return (
      <div className={styles.MenuBar}>
        <i
          className="icon iconfont iconbuoumaotubiao09"
          onClick={() => {
            this.setState({
              isMenuCollapse: !this.state.isMenuCollapse,
            });
          }}
        />
      </div>
    );
  }

  /**
   * renderMenu
   * @param defaultSelectedKeys
   * @param defaultOpenKeys
   * @return {*}
   */
  renderMenu({ defaultSelectedKeys, defaultOpenKeys }) {
    const { routes = [] } = this.props;

    return (
      <Menu
        className={styles.Menu}
        selectedKeys={defaultSelectedKeys.map((t) => t.path)}
        openKeys={defaultOpenKeys.map((t) => t.path)}
        onOpenChange={(openKeys) => {
          // 展开多个
          this.setState({
            openKeys: openKeys.map((key) => BasicLayout.fillKey(key, routes)),
          });

          // 只能展开一个
          // if (openKeys.length === 1) {
          //   this.setState({
          //     openKeys: [BasicLayout.fillKey(openKeys[0], routes)],
          //   });
          //
          //   return;
          // }
          //
          // let flag = true;
          //
          // // 1,2,3
          // for (let i = 0; i < openKeys.length - 1; i++) {
          //   if (openKeys[i + 1].indexOf(openKeys[i]) === -1) {
          //     flag = false;
          //     break;
          //   }
          // }
          //
          // if (flag) {
          //   this.setState({
          //     openKeys: openKeys.map((key) => BasicLayout.fillKey(key, routes)),
          //   });
          //
          //   return;
          // }
          //
          // this.setState({
          //   openKeys: openKeys
          //       .slice(openKeys.length - 1)
          //       .map((key) => BasicLayout.fillKey(key, routes)),
          // });
        }}
        onSelect={({ selectedKeys }) => {
          this.setState({
            selectedKeys: selectedKeys.map((key) => BasicLayout.fillKey(key, routes)),
          });
        }}
        mode="inline"
        theme="dark"
      >
        {this.renderMenuBar()}
        {this.renderMenuItem(routes)}
      </Menu>
    );
  }

  /**
   * renderBreadcrumb
   * @return {*}
   */
  renderBreadcrumb() {
    const { name, routes } = this.props;

    const selectKey = window.location.pathname;

    const path = [];
    BasicLayout.getPathBySelectKey({
      path,
      routes,
      selectKey,
    });

    const paths = path
      .filter((t) => !t.redirect)
      .sort((p1, p2) => {
        if (p1.path.length > p2.path.length) return 1;
        else if (p1.path.length < p2.path.length) return -1;
        else return 0;
      });

    return (
      <div className={styles.BreadcrumbWrap}>
        <Breadcrumb separator="/">
          <Breadcrumb.Item>{name}</Breadcrumb.Item>
          {paths.map((t, index) => (
            <Breadcrumb.Item key={t.path}>
              {index !== paths.length - 1 ? <Link to={t.path}>{t.name}</Link> : t.name}
            </Breadcrumb.Item>
          ))}
        </Breadcrumb>
      </div>
    );
  }

  /**
   * getDefault
   * @return {{defaultOpenKeys: Array, defaultSelectedKeys: Array}}
   */
  getDefault() {
    const { routes = [] } = this.props;
    const { openKeys, selectedKeys } = this.state;
    const defaultSelectedKeys = [];
    const defaultOpenKeys = [];
    BasicLayout.loopRoutes({
      defaultOpenKeys,
      defaultSelectedKeys,
      routes: routes.filter((t) => !t.redirect),
    });

    return {
      defaultSelectedKeys: selectedKeys.length ? selectedKeys : defaultSelectedKeys,
      defaultOpenKeys: openKeys.length ? openKeys : defaultOpenKeys,
    };
  }

  render() {
    const { defaultSelectedKeys, defaultOpenKeys } = this.getDefault();
    const { isMenuCollapse } = this.state;

    return (
      <div className={styles.BasicLayout}>
        <div
          className={classNames(styles.Fixed, styles.Sider, isMenuCollapse ? styles.Collapse : '')}
        >
          {this.renderMenu({
            defaultSelectedKeys,
            defaultOpenKeys,
          })}
        </div>
        <div className={styles.Auto}>
          {this.renderBreadcrumb({
            defaultSelectedKeys,
            defaultOpenKeys,
          })}
          <div className={styles.Auto}>{this.props.children}</div>
          <div className={styles.FooterWrap}>
            <Footer />
          </div>
        </div>
      </div>
    );
  }
}

BasicLayout.propTypes = {
  routes: PropTypes.array,
  name: PropTypes.string,
};

BasicLayout.defaultProps = {
  routes: [],
  name: '',
};

export default BasicLayout;
